

import os
VEHICLE_IMMOBILIZATION_API_URL = os.getenv("VEHICLE_IMMOBILIZATION_API_URL")
VEHICLE_IMMOBILIZATION_API_KEY = os.getenv("VEHICLE_IMMOBILIZATION_API_KEY")



import os
ROUTE_OPTIMIZATION_API_KEY = os.getenv("ROUTE_OPTIMIZATION_API_KEY")
