



version: '3'
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dispatcher_db
      POSTGRES_USER: dispatcher_user
      POSTGRES_PASSWORD: dispatcher_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:




version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
