version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dispatcher_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: dispatcher_frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: postgres
    container_name: dispatcher_db
    environment:
      POSTGRES_DB: dispatcher
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
